### ISSUE TITLE
Windows filePath parsing issue

### ISSUE THREAD

**Issue by ccjx** [Flet/standard-json#7]
Hi there, I've been trying out standard-json on a ReactJS project on Windows and I faced some issues with the filePath. Basically, the drive letter (i.e. "C:") is removed due to the incorrect regex in standard-json. 

I then passed the json generated into Sonarqube which failed to display the source files as it was not able to pick up the files with the paths "\\somedir\\somefile.js". 

I have corrected the issues and would like to submit a PR for your consideration.

Summary of my changes:
- Added 'minicat' library so that the 'cat' commands pass in windows (replaced them with minicat)
- Duplicated the data-verbose test case file and created a data-verbose-windows test case.
- Added the relevant test to verify that the new code will work correctly.
- Updated the regex as well as some of the code to ensure that both windows and linux/mac file paths are now handled properly.

Please feel free to share any feedback.

Edit:
Added a screenshot of errors seen on Azure Devops.
![Errors](https://user-images.githubusercontent.com/9329586/49565378-f3123200-f961-11e8-8672-78e9a3971a62.PNG)

> 2018-12-06T03:34:44.5087388Z WARN: No input file found for \a\1\s\frontends\versioning\src\App.js. No ESLint issues will be imported on this file.
The file is actually at D:\a\1\s\frontends\versioning\src\App.js

**Comment by feross** [comment]
Fixed by https://github.com/standard/standard-json/pull/8
